name: Cleanup Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.head.ref != github.event.pull_request.base.ref
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete head branch
        run: |
          gh api repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }} \
            -X DELETE
        env:
          GH_TOKEN: ${{ github.token }}
